// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://takwipwtzuxonaeaurqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRha3dpcHd0enV4b25hZWF1cnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODEwMDQsImV4cCI6MjA1ODY1NzAwNH0.EMJZ4MNPhWbWG93zqG4_Fz5s7WPOs5NVl1jfRSi7bnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);